Actualizamos la liga-justicia
jhonerlema/liga-justicia pull request #2
Opened 2023-09-19 22:21 UTC by jhonerlema1

2023-09-19 22:23 UTC, jhonerlema1 commented
Que bien que aceptaron el pull requests!

2023-09-19 23:50 UTC, jhonerlema commented on README.md
> -## Estos cambios son nuevos desde mi repositorio local
¿Por qué eliminó nuevos y puso viejos?

2023-09-20 00:01 UTC, jhonerlema requested changes
Jhonerlema1 por favor no elimine nuevo por viejo

2023-09-20 04:53 UTC, jhonerlema1 commented
@jhonerlema ya hice los cambios solicitados del README.md

2023-09-20 05:10 UTC, jhonerlema approved these changes
Excelente @jhonerlema1 todo es perfecto.

2023-09-20 05:13 UTC, jhonerlema commented
Perfecto, voy a unirlo!

2023-09-20 05:16 UTC, merged